### ISSUE TITLE
cast to double

### ISSUE THREAD

**Issue by hatemragab** [nanthakumaran-s/resize#1]
have i to cast all by 18.sp.toDouble() ? 
The argument type 'num' can't be assigned to the parameter type 'double?'.

**Comment by nanthakumaran-s** [comment]
It will be more clear if you provide some code sample for this issue...

**Comment by hatemragab** [comment]
check pull request

**Comment by nanthakumaran-s** [comment]
Thanks @hatemragab for contributing
