### ISSUE TITLE
please support max vh and vw

### ISSUE THREAD

**Issue by Silentdoer** [nanthakumaran-s/resize#3]
such as:
1.mv, then if 1.vw > 1.vh, 1.mv is 1.vw, else 1.mv is 1.vh

**Comment by nanthakumaran-s** [comment]
Hello, @Silentdoer Thanks for creating this issue. 

I have worked on your issue and created .mv unit. It has the functionality of returning max(.vh, .vw) for a given input. 

Check out this PR #4. If any assistance or malfunctions occurred on this new unit let me know. 

Finally thanks for contributing.

**Comment by nanthakumaran-s** [comment]
Published the changes. Kindly change the version to 1.0.0 to get .mv unit.

Let me keep this issue open for a couple of days. If any issues arise, share that in this issue.

Once again thanks for contributing.
