### ISSUE TITLE
How to set the height and width relative to the parent container

### ISSUE THREAD

**Issue by Silentdoer** [nanthakumaran-s/resize#5]
like 50% in css, and sorry for my english, why use allowtextScaling instead of allowTextScaling?

**Comment by Afaqkhan199** [comment]
Give your container a certain height and a certain width. Use FittedBox as a child of this Container. Place your desired widget inside this FittedBox and set the fit property to BoxFit.fill.

E.g.
Container(
height: _height,
width: _width,
child: FittedBox(
    fit: BoxFit.fill,
    child: YourWidgetHere()
    //this widget will take the height and width of it's FittedBox's parent's height and width respectively.
   ),
),
